language: node_js

git:
  depth: 3

matrix:
  - node_js: "7"
    env: SCRIPT=test
  - node_js: "6"
    env: SCRIPT=test

preinstall:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set spin false
  - yarn config set progress false

install:
  - yarn

test:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
