image: abstruse

matrix:
  - env: NODE_VERSION=8 TEST=0
  - env: NODE_VERSION=8 TEST=1
  - allow_failures:
    - env: NODE_VERSION=8 TEST=1

preinstall:
  - npm config set spin false
  - npm config set progress false
  - npm i
  - echo 'test'
  - echo $NODE_VERSION
  - echo $accessKeyId
  - echo $region

before_deploy:
  - nvm install 8
  - npm install
  - npm run pretest

script:
  - npm run-script test

deploy:
  - provider: elastic
  - application: "d3-test"
  - environmentName: "testEnv"
  - solutionStackName: "64bit Amazon Linux 2017.09 v4.4.0 running Node.js"

install:
  - nvm install $NODE_VERSION
  - npm install
  - echo 'test'
  - echo $NODE_VERSION
  - echo $region
  - echo $accessKeyId

cache:
  - node_modules
