image: abstruse

matrix:
  - env: NODE_VERSION: 8

preinstall:
  - npm config set spin false
  - npm config set progress false

install:
  - nvm install $NODE_VERSION
  - npm install

test:
  - npm run-script test

cache
  - node_modules
