language: node_js

git:
  depth: 3

matrix:
  - node_js: "8"
    env: SCRIPT=test

preinstall:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

test:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
